version: '3.9'

services:
  postgresql:
    container_name: estudos-nestjs-pg
    image: bitnami/postgresql:latest
    ports:
      - ${POSTGRESQL_PORT}:5432
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./.docker/setup-test-db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
